# Usar una imagen base ligera de Node.js
FROM node:18-alpine

# Establecer el directorio de trabajo dentro del contenedor --
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias de producción
RUN npm install --omit=dev

# Copiar el resto del código de la aplicación
COPY . .

# (NUEVA LÍNEA) Instalar curl, que no viene en alpine por defecto
RUN apk add --no-cache curl

EXPOSE 3000

# (NUEVO) Chequeo de salud
HEALTHCHECK --interval=30s --timeout=3s \
  CMD curl -f http://localhost:3000/health || exit 1

# Comando para iniciar la aplicación
CMD [ "npm", "start" ]